trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - jcat/*
      - azure-pipelines.yml
      - requirements.txt

pr: none

pool:
  vmImage: 'windows-latest'

stages:
  - stage: CI
    jobs: 
    - job: Build
      steps:
        - task: UseGitVersion@5
          inputs:
            versionSpec: 5.x
            useConfigFile: true
            configFilePath: GitVersion.yml

        - task: UsePythonVersion@0
          inputs:
            versionSpec: 3.8.3

        - script: python -m pip install -r requirements.txt
          displayName: Install dependencies

        - script: python setup.py bdist_msi
          displayName: Build executable

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/dist
            artifactName: publish

  - stage: Release
    dependsOn: CI
    condition: succeeded('CI')
    jobs:
    - job: release
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      steps:
        - task: DownloadPipelineArtifact@2
          displayName: Restore Pipeline Artifacts

        - task: GitHubRelease@1
          displayName: Create a GitHub GitHubRelease
          condition: startswith(variables['Build.SourceBranch'], 'refs/tags/v')
          inputs:
            gitHubConnection: 'chelnak'
            title: jcat
            repositoryName: 'chelnak/jcat'
            assets: "$(Pipeline.Workspace)/publish/*.msi"
