trigger:
  batch: true
  branches:
    include:
      - "*"
  tags:
    include:
      - "v*"      
  paths:
    include:
      - jcat/*
      - azure-pipelines.yml
      - requirements.txt

pr: none

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: CI
    jobs: 
    - job: GenerateBuildNumber
      steps:
        - task: UseGitVersion@5
          inputs:
            versionSpec: 5.x
            useConfigFile: true
            configFilePath: GitVersion.yml

        - pwsh: Write-Output "##vso[task.setvariable variable=GITVERSION_SEMVER;isOutput=true]$ENV:GITVERSION_SEMVER"
          name: version

    - job: BuildGeneric
      dependsOn: GenerateBuildNumber
      variables:
        GITVERSION_SEMVER: $[ dependencies.GenerateBuildNumber.outputs['version.GITVERSION_SEMVER'] ]
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: 3.8.3

        - pwsh: $(System.DefaultWorkingDirectory)/scripts/build.ps1
          displayName: Build artifacts
          env:
            GITVERSION_SEMVER: $(GITVERSION_SEMVER)

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/artifacts
            artifactName: publish

  - stage: Release
    dependsOn: CI
    condition: succeeded('CI')
    jobs:
    - job: release
      condition: startswith(variables['Build.SourceBranch'], 'refs/tags/v')
      steps:      
        - task: DownloadPipelineArtifact@2
          displayName: Restore Pipeline Artifacts

        - script: 'pip install twine'
        - task: TwineAuthenticate@0
          inputs:
            externalFeeds: 'pypi-jcat'
        - script: 'twine upload -r {pypi-jcat/jcat} --config-file $(PYPIRC_PATH) "$(Pipeline.Workspace)/publish/*"'

        - task: GitHubRelease@1
          displayName: Create a GitHub GitHubRelease
          condition: 
          inputs:
            gitHubConnection: 'chelnak'
            title: jcat
            repositoryName: 'chelnak/jcat'
            assets: "$(Pipeline.Workspace)/publish/*.*"
